create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id),
  store_id uuid not null references public.stores(id),
  expense_number text not null,
  category text not null,
  amount numeric(14,2) not null check (amount > 0),
  expense_date date not null default current_date,
  payment_method text not null default 'cash',
  reference text,
  notes text,
  status text not null default 'completed' check (status in ('completed','cancelled')),
  created_by uuid not null,
  created_at timestamptz not null default now(),
  cancelled_at timestamptz,
  cancelled_by uuid,
  cancel_reason text,
  unique (organization_id, expense_number)
);

alter table public.expenses enable row level security;
drop policy if exists expenses_org_access on public.expenses;
create policy expenses_org_access on public.expenses for all to authenticated
using (private.is_org_store_member(organization_id,store_id))
with check (private.is_org_store_member(organization_id,store_id));

create or replace function private.next_expense_number(p_organization_id uuid)
returns text language plpgsql security definer set search_path=''
as $$
declare n bigint;
begin
  if not exists(select 1 from public.organization_members where organization_id=p_organization_id and user_id=auth.uid() and status='active') then
    raise exception 'organization access denied';
  end if;
  insert into private.document_sequences(organization_id,document_type,next_number)
  values(p_organization_id,'expense',2)
  on conflict (organization_id,document_type) do update set next_number=private.document_sequences.next_number+1,updated_at=now()
  returning next_number-1 into n;
  return 'EXP-'||lpad(n::text,6,'0');
end $$;

create or replace function private.create_expense(
 p_organization_id uuid,p_store_id uuid,p_category text,p_amount numeric,
 p_expense_date date default current_date,p_payment_method text default 'cash',
 p_reference text default null,p_notes text default null
) returns public.expenses
language plpgsql security definer set search_path=public,private
as $$
declare v public.expenses;
begin
 if auth.uid() is null or not private.is_org_store_member(p_organization_id,p_store_id) then raise exception 'access denied'; end if;
 if coalesce(trim(p_category),'')='' then raise exception 'expense category is required'; end if;
 if p_amount is null or p_amount<=0 then raise exception 'expense amount must be greater than zero'; end if;
 insert into public.expenses(organization_id,store_id,expense_number,category,amount,expense_date,payment_method,reference,notes,status,created_by)
 values(p_organization_id,p_store_id,private.next_expense_number(p_organization_id),trim(p_category),round(p_amount,2),coalesce(p_expense_date,current_date),coalesce(nullif(trim(p_payment_method),''),'cash'),nullif(trim(p_reference),''),nullif(trim(p_notes),''),'completed',auth.uid())
 returning * into v;
 insert into public.audit_logs(organization_id,store_id,actor_user_id,action,entity_type,entity_id,metadata)
 values(p_organization_id,p_store_id,auth.uid(),'expense.created','expense',v.id::text,jsonb_build_object('amount',v.amount,'category',v.category));
 return v;
end $$;

create or replace function public.create_expense(uuid,uuid,text,numeric,date,text,text,text)
returns public.expenses language sql security invoker set search_path=public,private
as $$ select private.create_expense($1,$2,$3,$4,$5,$6,$7,$8); $$;

create or replace function private.cancel_expense(p_organization_id uuid,p_expense_id bigint,p_reason text)
returns public.expenses
language plpgsql security definer set search_path=public,private
as $$
declare v public.expenses;
begin
 if auth.uid() is null then raise exception 'authentication required'; end if;
 select * into v from public.expenses where id=p_expense_id and organization_id=p_organization_id for update;
 if not found or not private.is_org_store_member(p_organization_id,v.store_id) then raise exception 'expense not found or access denied'; end if;
 if v.status='cancelled' then raise exception 'expense already cancelled'; end if;
 if coalesce(trim(p_reason),'')='' then raise exception 'cancellation reason is required'; end if;
 update public.expenses set status='cancelled',cancelled_at=now(),cancelled_by=auth.uid(),cancel_reason=trim(p_reason) where id=v.id returning * into v;
 insert into public.audit_logs(organization_id,store_id,actor_user_id,action,entity_type,entity_id,metadata)
 values(p_organization_id,v.store_id,auth.uid(),'expense.cancelled','expense',v.id::text,jsonb_build_object('reason',v.cancel_reason,'amount',v.amount));
 return v;
end $$;

create or replace function public.cancel_expense(uuid,bigint,text)
returns public.expenses language sql security invoker set search_path=public,private
as $$ select private.cancel_expense($1,$2,$3); $$;

revoke all on function private.next_expense_number(uuid) from public,anon,authenticated;
revoke all on function private.create_expense(uuid,uuid,text,numeric,date,text,text,text) from public,anon,authenticated;
revoke all on function private.cancel_expense(uuid,bigint,text) from public,anon,authenticated;
grant execute on function public.create_expense(uuid,uuid,text,numeric,date,text,text,text) to authenticated;
grant execute on function public.cancel_expense(uuid,bigint,text) to authenticated;
grant select on public.expenses to authenticated;