-- Commercial V1: purchase returns
create table if not exists public.purchase_returns (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  store_id uuid not null,
  purchase_receipt_id bigint not null,
  supplier_id bigint,
  return_number text not null,
  total numeric not null default 0 check (total >= 0),
  refund_amount numeric not null default 0 check (refund_amount >= 0),
  refund_payment_method text,
  refund_reference text,
  reason text not null,
  notes text,
  status text not null default 'completed' check (status in ('completed','cancelled')),
  created_at timestamptz not null default now(),
  created_by uuid
);
create unique index if not exists purchase_returns_org_number_uq on public.purchase_returns(organization_id, return_number);
create table if not exists public.purchase_return_items (
  id bigint generated by default as identity primary key,
  purchase_return_id bigint not null references public.purchase_returns(id),
  purchase_receipt_item_id bigint not null,
  product_id bigint not null,
  quantity integer not null check (quantity > 0),
  unit_cost numeric not null check (unit_cost >= 0),
  total numeric not null check (total >= 0)
);
create table if not exists public.supplier_refunds (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  store_id uuid not null,
  supplier_id bigint not null,
  purchase_return_id bigint not null references public.purchase_returns(id),
  amount numeric not null check (amount > 0),
  payment_method text not null,
  reference text,
  notes text,
  refunded_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists purchase_returns_receipt_idx on public.purchase_returns(organization_id,purchase_receipt_id);
create index if not exists purchase_return_items_return_idx on public.purchase_return_items(purchase_return_id);
create index if not exists supplier_refunds_return_idx on public.supplier_refunds(organization_id,purchase_return_id);

create or replace function private.next_purchase_return_number(p_organization_id uuid)
returns text language plpgsql security definer set search_path=''
as $$
declare v_next bigint;
begin
  insert into public.document_sequences(organization_id,document_type,next_number)
  values(p_organization_id,'purchase_return',1)
  on conflict (organization_id,document_type) do nothing;
  update public.document_sequences set next_number=next_number+1,updated_at=now()
  where organization_id=p_organization_id and document_type='purchase_return'
  returning next_number-1 into v_next;
  return 'PR-'||lpad(v_next::text,6,'0');
end;
$$;

create or replace function private.return_purchase_items(
  p_organization_id uuid,p_store_id uuid,p_purchase_receipt_id bigint,p_items jsonb,p_reason text,
  p_refund_amount numeric default 0,p_refund_payment_method text default 'cash',
  p_refund_reference text default null,p_notes text default null
) returns jsonb language plpgsql security definer set search_path='public','private'
as $$
declare
  v_purchase public.purchase_receipts%rowtype;
  v_item jsonb; v_ri public.purchase_receipt_items%rowtype; v_product public.store_products%rowtype;
  v_return public.purchase_returns%rowtype; v_qty integer; v_total numeric:=0; v_refund numeric:=coalesce(p_refund_amount,0);
  v_return_number text; v_refund_id bigint; v_returned_before integer; v_available integer;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not private.is_org_store_member(p_organization_id,p_store_id) then raise exception 'organization/store access denied'; end if;
  if not private.has_org_permission(p_organization_id,'inventory.adjust') then raise exception 'inventory.adjust permission required'; end if;
  if v_refund>0 and not private.has_org_permission(p_organization_id,'supplier_payments.create') then raise exception 'supplier_payments.create permission required'; end if;
  if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception 'return reason is required'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'return items are required'; end if;
  if v_refund<0 then raise exception 'refund amount must be nonnegative'; end if;

  select * into v_purchase from public.purchase_receipts
  where id=p_purchase_receipt_id and organization_id=p_organization_id and store_id=p_store_id for update;
  if not found then raise exception 'purchase receipt not found'; end if;
  if v_purchase.status<>'completed' then raise exception 'only completed purchases can be returned'; end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    select * into v_ri from public.purchase_receipt_items
    where id=(v_item->>'purchase_receipt_item_id')::bigint and receipt_id=v_purchase.id for update;
    if not found then raise exception 'purchase receipt item not found'; end if;
    v_qty:=(v_item->>'quantity')::integer;
    if v_qty<=0 then raise exception 'return quantity must be positive'; end if;
    select coalesce(sum(pri.quantity),0)::integer into v_returned_before
    from public.purchase_return_items pri join public.purchase_returns pr on pr.id=pri.purchase_return_id
    where pri.purchase_receipt_item_id=v_ri.id and pr.status='completed';
    v_available:=v_ri.quantity-v_returned_before;
    if v_qty>v_available then raise exception 'return quantity exceeds remaining purchased quantity'; end if;
    select * into v_product from public.store_products where store_id=p_store_id and product_id=v_ri.product_id for update;
    if not found then raise exception 'product is not assigned to this store'; end if;
    if v_product.quantity<v_qty then raise exception 'return quantity exceeds current stock'; end if;
    v_total:=v_total+(v_qty*v_ri.unit_cost);
  end loop;

  if v_refund>v_total then raise exception 'refund amount cannot exceed returned purchase value'; end if;
  if v_refund>0 and nullif(btrim(coalesce(p_refund_payment_method,'')),'') is null then raise exception 'refund payment method is required'; end if;

  v_return_number:=private.next_purchase_return_number(p_organization_id);
  insert into public.purchase_returns(organization_id,store_id,purchase_receipt_id,supplier_id,return_number,total,refund_amount,
    refund_payment_method,refund_reference,reason,notes,created_by)
  values(p_organization_id,p_store_id,v_purchase.id,v_purchase.supplier_id,v_return_number,v_total,v_refund,
    case when v_refund>0 then btrim(p_refund_payment_method) else null end,
    nullif(btrim(coalesce(p_refund_reference,'')),''),btrim(p_reason),nullif(btrim(coalesce(p_notes,'')),''),auth.uid())
  returning * into v_return;

  for v_item in select value from jsonb_array_elements(p_items) loop
    select * into v_ri from public.purchase_receipt_items where id=(v_item->>'purchase_receipt_item_id')::bigint and receipt_id=v_purchase.id for update;
    v_qty:=(v_item->>'quantity')::integer;
    insert into public.purchase_return_items(purchase_return_id,purchase_receipt_item_id,product_id,quantity,unit_cost,total)
    values(v_return.id,v_ri.id,v_ri.product_id,v_qty,v_ri.unit_cost,v_qty*v_ri.unit_cost);
    update public.store_products set quantity=quantity-v_qty,updated_at=now()
    where store_id=p_store_id and product_id=v_ri.product_id;
    insert into public.inventory_movements(product_id,organization_id,store_id,movement_type,quantity_change,reference_type,reference_id,notes)
    values(v_ri.product_id,p_organization_id,p_store_id,'return',-v_qty,'purchase_return',v_return.id,'Stock returned to supplier: '||btrim(p_reason));
  end loop;

  if v_refund>0 then
    insert into public.supplier_refunds(organization_id,store_id,supplier_id,purchase_return_id,amount,payment_method,reference,notes)
    values(p_organization_id,p_store_id,v_purchase.supplier_id,v_return.id,v_refund,btrim(p_refund_payment_method),
      nullif(btrim(coalesce(p_refund_reference,'')),''),'Supplier refund for purchase return '||v_return.return_number)
    returning id into v_refund_id;
  end if;

  perform private.write_audit_log(p_organization_id,p_store_id,'purchase.returned','purchase_return',v_return.id::text,
    jsonb_build_object('return_number',v_return_number,'purchase_receipt_id',v_purchase.id,'total',v_total,
      'refund_amount',v_refund,'refund_id',v_refund_id,'reason',btrim(p_reason)));

  return jsonb_build_object('id',v_return.id,'return_number',v_return_number,'total',v_total,'refund_amount',v_refund,'refund_id',v_refund_id,'status','completed');
end;
$$;

create or replace function public.return_purchase_items(
  p_organization_id uuid,p_store_id uuid,p_purchase_receipt_id bigint,p_items jsonb,p_reason text,
  p_refund_amount numeric default 0,p_refund_payment_method text default 'cash',
  p_refund_reference text default null,p_notes text default null
) returns jsonb language plpgsql security invoker set search_path='public','private'
as $$
begin
  return private.return_purchase_items(p_organization_id,p_store_id,p_purchase_receipt_id,p_items,p_reason,
    p_refund_amount,p_refund_payment_method,p_refund_reference,p_notes);
end;
$$;
revoke execute on function public.return_purchase_items(uuid,uuid,bigint,jsonb,text,numeric,text,text,text) from public,anon;
grant execute on function public.return_purchase_items(uuid,uuid,bigint,jsonb,text,numeric,text,text,text) to authenticated;


create or replace function private.purchase_return_details(
 p_organization_id uuid,p_store_id uuid,p_purchase_receipt_id bigint
) returns jsonb language plpgsql security definer set search_path='public','private'
as $$
declare v_purchase public.purchase_receipts%rowtype;
begin
 if auth.uid() is null then raise exception 'authentication required'; end if;
 if not private.is_org_store_member(p_organization_id,p_store_id) then raise exception 'organization/store access denied'; end if;
 if not private.has_org_permission(p_organization_id,'purchases.view') then raise exception 'purchases.view permission required'; end if;
 select * into v_purchase from public.purchase_receipts where id=p_purchase_receipt_id and organization_id=p_organization_id and store_id=p_store_id;
 if not found then raise exception 'purchase receipt not found'; end if;
 return jsonb_build_object(
  'id',v_purchase.id,'receipt_number',v_purchase.receipt_number,'supplier_invoice_number',v_purchase.supplier_invoice_number,
  'status',v_purchase.status,'total',v_purchase.total,
  'items',coalesce((select jsonb_agg(jsonb_build_object(
    'purchase_receipt_item_id',pri.id,'product_id',pri.product_id,'product_name',p.name,
    'quantity',pri.quantity,'unit_cost',pri.unit_cost,
    'returned_quantity',coalesce((select sum(pri2.quantity) from public.purchase_return_items pri2 join public.purchase_returns pr2 on pr2.id=pri2.purchase_return_id where pri2.purchase_receipt_item_id=pri.id and pr2.status='completed'),0),
    'available_quantity',pri.quantity-coalesce((select sum(pri2.quantity) from public.purchase_return_items pri2 join public.purchase_returns pr2 on pr2.id=pri2.purchase_return_id where pri2.purchase_receipt_item_id=pri.id and pr2.status='completed'),0)
  ) order by pri.id) from public.purchase_receipt_items pri join public.products p on p.id=pri.product_id where pri.receipt_id=v_purchase.id),'[]'::jsonb)
 );
end; $$;
create or replace function public.purchase_return_details(p_organization_id uuid,p_store_id uuid,p_purchase_receipt_id bigint)
returns jsonb language plpgsql security invoker set search_path='public','private'
as $$ begin return private.purchase_return_details(p_organization_id,p_store_id,p_purchase_receipt_id); end; $$;
revoke execute on function public.purchase_return_details(uuid,uuid,bigint) from public,anon;
grant execute on function public.purchase_return_details(uuid,uuid,bigint) to authenticated;
