CREATE OR REPLACE FUNCTION public.inventory_valuation_report(p_organization_id uuid, p_store_id uuid, p_from timestamp with time zone DEFAULT NULL::timestamp with time zone, p_to timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_current jsonb; v_flow jsonb; v_products jsonb;
begin
select jsonb_build_object('inventory_units',coalesce(sum(sp.quantity),0),'inventory_value',coalesce(sum(case when sp.cost_known then sp.quantity*sp.average_cost else 0 end),0),'products_with_stock',count(*) filter(where sp.quantity>0),'products_without_cost',count(*) filter(where sp.quantity>0 and not sp.cost_known))
into v_current from public.store_products sp join public.products pr on pr.id=sp.product_id where sp.store_id=p_store_id and pr.organization_id=p_organization_id;
select jsonb_build_object('purchase_units',coalesce(sum(pri.quantity),0),'purchase_value',coalesce(sum(pri.quantity*pri.unit_cost),0),'sold_units',coalesce((select sum(si.quantity) from public.sale_items si join public.sales s on s.id=si.sale_id where s.organization_id=p_organization_id and s.store_id=p_store_id and s.status in('completed','partially_returned','fully_returned') and si.unit_cost is not null and(p_from is null or s.created_at>=p_from)and(p_to is null or s.created_at<p_to)),0),'cogs',coalesce((select sum(si.cost_total) from public.sale_items si join public.sales s on s.id=si.sale_id where s.organization_id=p_organization_id and s.store_id=p_store_id and s.status in('completed','partially_returned','fully_returned') and si.unit_cost is not null and(p_from is null or s.created_at>=p_from)and(p_to is null or s.created_at<p_to)),0),'returned_units',coalesce((select sum(sri.quantity) from public.sale_return_items sri join public.sale_returns sr on sr.id=sri.return_id where sr.organization_id=p_organization_id and sr.store_id=p_store_id and(p_from is null or sr.created_at>=p_from)and(p_to is null or sr.created_at<p_to)),0),'returned_cost_value',coalesce((select sum(sri.quantity*si.unit_cost) from public.sale_return_items sri join public.sale_returns sr on sr.id=sri.return_id join public.sale_items si on si.id=sri.sale_item_id where sr.organization_id=p_organization_id and sr.store_id=p_store_id and si.unit_cost is not null and(p_from is null or sr.created_at>=p_from)and(p_to is null or sr.created_at<p_to)),0)) into v_flow from public.purchase_receipt_items pri join public.purchase_receipts prc on prc.id=pri.receipt_id where prc.organization_id=p_organization_id and prc.store_id=p_store_id and(p_from is null or prc.created_at>=p_from)and(p_to is null or prc.created_at<p_to);
select coalesce(jsonb_agg(to_jsonb(x) order by x.inventory_value desc nulls last,x.product_id),'[]'::jsonb) into v_products from(select sp.product_id,pr.name product_name,sp.quantity,sp.average_cost,sp.cost_known,case when sp.cost_known then sp.quantity*sp.average_cost else null end inventory_value from public.store_products sp join public.products pr on pr.id=sp.product_id where sp.store_id=p_store_id and pr.organization_id=p_organization_id limit 100)x;
return jsonb_build_object('period',jsonb_build_object('from',p_from,'to',p_to),'current_inventory',v_current,'period_flow',v_flow,'products',v_products);
end;$function$;
